language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules  

branches:
  only:
    - gomix
    - master

after_success:
  - npx sync-glitch-cli

notifications:
  email:
    on_failure: always